#!/bin/sh

mit-scheme --compiler -heap 6000 --batch-mode --no-init-file --eval \
 "(begin
    (if (lexical-unbound? system-global-environment 'let-fluids)
      (set! load/suppress-loading-message? #t)
      (set-fluid! load/suppress-loading-message? #t))
    (load \"load\")
    (load \"test/load\")
    (show-time run-registered-tests)
    (newline)
    (flush-output)
    (%exit 0))"
