#!/usr/bin/env ruby

# -*- ruby-mode -*-

def root
  ENV["SCMUTILS_ROOT"] || "/usr/local/scmutils"
end

def scheme
  scheme = "#{root}/mit-scheme/bin/scheme"
end

def try_by_executable
  fixed_opts = ["--library",
    "#{root}/mit-scheme/lib",
    "--heap",
    "6000",
    "--band",
    "edwin-mechanics.com"
  ]

  if File.executable?(scheme)
    exec scheme, *(fixed_opts + ARGV)
  end
end

def mechanics_band
  "/scmutils/linux/edwin-mechanics.com"
end

def try_by_band(band)
  fixed_opts = ["-constant",
    "2000",
    "-heap",
    "10000",
    "-band",
    band
  ]
  if File.exist?(band)
    exec "mit-scheme", *(fixed_opts + ARGV)
  end
end

try_by_executable
try_by_band("/sw" + mechanics_band)
try_by_band("/usr/local"+ mechanics_band)
puts "No Scheme at #{scheme} and no Mechanics bands at {/sw|/usr/local}#{mechanics_band} :("

