require "#{File.dirname(__FILE__)}/rake-latex.rb"

def rstify filename
  file "#{filename}.html" => ["#{filename}.rst", "style.css"] do
    sh "rst2html --stylesheet style.css #{filename}.rst > #{filename}.html"
  end
  task :doc => "#{filename}.html"
end

rstify "programmer-guide"
rstify "revised"

task :doc => "revised.pdf"

pdflatex "revised"
autobib "revised"

file "revised-revised.tex" => "revised.tex" do
  sh "cat revised.tex | grep -v hypertarget | grep -v pdfbookmark > revised-revised.tex"
end

file "revised-revised/index.html" => "revised-revised.tex" do
  sh "latex revised-revised.tex"
  sh "latex2html revised-revised"
end

task :doc => "revised-revised/index.html"
