def rstify filename
  file "#{filename}.html" => ["#{filename}.rst", "style.css"] do
    sh "rst2html --stylesheet style.css #{filename}.rst > #{filename}.html"
  end
  task :doc => "#{filename}.html"
end

file "revised.rst" => "revised.txt" do
  sh "cp revised.txt revised.rst"
end

rstify "programmer-guide"
rstify "revised"
