require "#{File.dirname(__FILE__)}/rake-latex.rb"

def rstify filename
  file "#{filename}.html" => ["#{filename}.rst", "style.css"] do
    sh "rst2html --stylesheet style.css #{filename}.rst > #{filename}.html"
  end
  task :doc => "#{filename}.html"
end

rstify "programmer-guide"

task :doc => "revised.pdf"

pdflatex "revised"
autobib "revised"

file "revised-html.tex" => "revised.tex" do
  sh "cat revised.tex | grep -v hypertarget | grep -v pdfbookmark > revised-html.tex"
end

file "revised-html/revised-html.html" => "revised-html.tex" do
  sh "latex revised-html.tex"
  sh "bibtex revised-html"
  sh "latex2html revised-html"
end

task :doc => "revised.html"

file "revised.html" => "revised-html/revised-html.html" do
  sh "cp revised-html/revised-html.html revised-html.html"
end
