### ----------------------------------------------------------------------
### Copyright 2009-2010 Alexey Radul.
### ----------------------------------------------------------------------
### This file is part of Propagator Network Prototype.
### 
### Propagator Network Prototype is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
### 
### Propagator Network Prototype is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
### 
### You should have received a copy of the GNU General Public License
### along with Propagator Network Prototype.  If not, see <http://www.gnu.org/licenses/>.
### ----------------------------------------------------------------------

def scheme command
  sh "mit-scheme --compiler -heap 6000 --batch-mode --no-init-file --eval '(set! load/suppress-loading-message? #t)' --eval '(begin #{command} (%exit 0))'"
end

def dot_dump command, filename
  task "#{filename}.dot" do
    scheme "(load \"load\") (initialize-scheduler) #{command} (prop:dot:write-graph-to-file \"#{filename}.dot\")"
  end
  task "dot-graphs" => "#{filename}.dot"
end

def dot_process filename, format
  file "#{filename}.#{format}" => "#{filename}.dot" do
    sh "dot -T#{format} -o #{filename}.#{format} #{filename}.dot"
  end
end

def picture command, filename
  dot_dump command, filename
  dot_process(filename, "svg")
  dot_process(filename, "png")
end

picture "(multiple-dwelling)", "multiple-dwelling"
picture "(build-network)", "riddle-of-the-knights"
picture "(build-albatross-network)", "albatross-conundrum"
