### ----------------------------------------------------------------------
### Copyright 2009-2010 Alexey Radul.
### ----------------------------------------------------------------------
### This file is part of Propagator Network Prototype.
### 
### Propagator Network Prototype is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
### 
### Propagator Network Prototype is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
### 
### You should have received a copy of the GNU General Public License
### along with Propagator Network Prototype.  If not, see <http://www.gnu.org/licenses/>.
### ----------------------------------------------------------------------

def scheme command
  sh "mit-scheme --compiler -heap 6000 --batch-mode --no-init-file --eval '(set! load/suppress-loading-message? #t)' --eval '(begin #{command} (%exit 0))'"
end

task "multiple-dwelling.dot" do
  scheme "(load \"load\") (initialize-scheduler) (multiple-dwelling) (prop:dot:write-graph-to-file \"multiple-dwelling.dot\")"
end
