#!/bin/sh

exec ../extensions/mechanics --compiler -heap 6000 --batch-mode --no-init-file --eval \
 "(begin
    (if (lexical-unbound? system-global-environment 'let-fluids)
      (set! load/suppress-loading-message? #t)
      (set-fluid! load/suppress-loading-message? #t))
    (load \"load\")
    (load \"test/mechanics-load\")
    (run-tests-and-exit))"
